[package]
name = "triangles"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://github.com/bsikar/Rust_Projects/tree/main/triangles"
license = "MIT"
edition = "2018"

[dependencies]
