[package]
name = "snake"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://github.com/bsikar/Rust_Projects/tree/main/snake"
license = "MIT"
edition = "2018"

[dependencies]
rand = "0.8.0"
ncurses = "5.101.0"
