[package]
name = "hello_world"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://github.com/pissmilk/Rust_Projects/tree/main/hello_world"
license = "MIT"
edition = "2018"

[dependencies]
