[package]
name = "snake_gui"
version = "0.1.0"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
homepage = "https://github.com/bsikar/Rust_Projects/tree/main/snake_gui"
license = "MIT"
edition = "2018"

[dependencies]
rand = "0.8.0"
piston_window = "0.119.0"
piston2d-opengl_graphics = "0.78.0"
