[package]
name = "pre-cal"
version = "0.1.0"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
homepage = "https://github.com/bsikar/Rust_Projects/tree/main/pre-cal"
license = "MIT"
edition = "2018"

[dependencies]
