[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Brighton Sikarskie <brighton.sikarskie@tuta.io>"]
homepage = "https://github.com/pissmilk/Rust_Projects/tree/main/guessing_game"
license = "MIT"
edition = "2018"

[dependencies]
rand = "0.6.0"
