[package]
name = "hashmap_and_files"
version = "0.1.0"
authors = ["Brighton Sikarskie <bsikar@tuta.io>"]
edition = "2018"
homepage = "https://github.com/bsikar/Rust_Projects/tree/main/hashmap_and_files"
license = "MIT"

[dependencies]
